General:
    MODEL_NAME: WIKG_MIL
    seed: 2024
    num_classes: 6
    num_epochs: 30
    device: 6
    num_workers: 4
    best_model_metric: macro_auc  
    earlystop: 
        use: True
        patience: 5
        metric: macro_auc  

Dataset:
    DATASET_NAME: tztv_gleason_score_site_GS345
    # to use train-val-test, open dataset_csv_dir
    # to use k-fold train-val/k-fold train-val then test, open dataset_root_dir
    
    # dataset_csv_path: /path/to/your/dataset.csv
    dataset_root_dir: /n/archive00/labs/IT/GDC/xihao/HIPT-master-org/2-Weakly-Supervised-Subtyping/MIL_BASELINE-main/datasets/tztv_gleason_score_site_GS345
    VIST: False # if your val is test, set it to True
    
Logs:
    log_root_dir: /n/archive00/labs/IT/GDC/xihao/HIPT-master-org/2-Weakly-Supervised-Subtyping/MIL_BASELINE-main/log_dir/

Model:
    in_dim: 1024 # depend on the pt dimensions，such resnet50——>1024 vit_s——>384
    dim_hidden: 512
    topk: 6
    agg_type: bi-interaction
    pool: attn
    dropout: 0.1
    act: LeakyReLU  
    optimizer:
        which: adam    # adam or adamw
        adam_config:
            lr: 0.0002
            weight_decay: 0.00001
        adamw_config:
            lr: 0.0002
            weight_decay: 0.00001
    criterion: ce  # ce
    scheduler:
        warmup: 2
        which: step  # [step, cosine,multi_step,exponential]
        step_config:
            step_size: 3 # absolute step size, should ensure that step_size > warmup
            gamma: 0.9
        multi_step_config:
            milestones: [20, 30, 40] # absolute milestones, should ensure that milestones > warmup
            gamma: 0.9
        exponential_config:
            gamma: 0.9 # begin after warmup
        cosine_config:
            T_max: 10 # interval of cosine annealing, begin after warmup
            eta_min: 0.0001
        

    
     
